// GENERATED by scripts/write-version.mjs from this package's package.json — do not edit by hand.
// Re-run `pnpm run version:patch` / `version:minor` (which regenerate it) to change the version.

/**
 * The published version of `@agora-sdk/secure-chat-core` as a `major.minor.patch` string,
 * re-exported by the platform packages (`@agora-sdk/secure-chat-react-js`, `…-react-native`,
 * `…-expo`). Useful for diagnostics — e.g. logging which SDK build an app actually loaded when a
 * stale bundle is suspected.
 *
 * @example
 * ```ts
 * import { VERSION } from "@agora-sdk/secure-chat-react-js";
 * console.log(`secure-chat SDK ${VERSION}`);
 * ```
 */
export const VERSION = "0.6.6";
