// Regenerate packages/secure-chat/core/src/version.ts from that package's package.json `version`, so
// the exported VERSION constant can never drift from the published version. The platform packages
// (react-js / react-native / expo) re-export it via `export *`, so this one file covers them all.
//
// Wired into the `version:patch` / `version:minor` scripts (runs right after the bump). Safe to run
// anytime — it's idempotent and only rewrites the one generated file.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkgDir = join(root, "packages/secure-chat/core");
const { version } = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8"));

const content = `// GENERATED by scripts/write-version.mjs from this package's package.json — do not edit by hand.
// Re-run \`pnpm run version:patch\` / \`version:minor\` (which regenerate it) to change the version.

/**
 * The published version of \`@agora-sdk/secure-chat-core\` as a \`major.minor.patch\` string,
 * re-exported by the platform packages (\`@agora-sdk/secure-chat-react-js\`, \`…-react-native\`,
 * \`…-expo\`). Useful for diagnostics — e.g. logging which SDK build an app actually loaded when a
 * stale bundle is suspected.
 *
 * @example
 * \`\`\`ts
 * import { VERSION } from "@agora-sdk/secure-chat-react-js";
 * console.log(\`secure-chat SDK \${VERSION}\`);
 * \`\`\`
 */
export const VERSION = ${JSON.stringify(version)};
`;

writeFileSync(join(pkgDir, "src/version.ts"), content);
console.log(`wrote secure-chat-core VERSION = ${version}`);
